language: python
python:
  - "3.5"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python3 -m unittest discover
  - coverage run -m unittest discover
after_success:
  - codecov